### ISSUE TITLE
Test the RF coil for me please 

### ISSUE THREAD

**Issue by arha** [zacharyweiss/magspoof_flipper#4]
Can you please run a test against your MSR with the new `MagTxLFCarrier` TX method? Perhaps do a few sanity checks yourself if the messages are fine. There's a new branch with a rather crude implementation which pulses the LF coil at 125k for `LF_PULSE_US` microseconds:`tx-lf-carrier`. Still waiting on Amazon for my stuff, sadly, otherwise I would have done this myself.

Current RF emulation on a 125khz tuned coil + track 1 gives me about 4Vpp
![image](https://user-images.githubusercontent.com/4208594/216775410-728ffa9d-85c7-44a5-a5ca-f936451e22e4.png)

Charging the LF coil for 60us (with a 200us bit clock) boosts my reading to about 9V, that's 33% duty cycle, that should be about ~5 times of a stronger field. Note this is track 2 of Samy's test card. 
![image](https://user-images.githubusercontent.com/4208594/216775485-9f9e8577-c71c-4162-ae3f-42e96c246f5f.png)

Counting past the 25 zeroes, splitting the count at every zero bit, we should be getting the original track again (5, 3, 1, 1, 3, 1, 1, 3, 1...). This is posted as a sanity check for myself.
![image](https://camo.githubusercontent.com/57b763230cdc66f9ad5aecfa04cc047178d4852fa892f429b2176168988d2fa4/687474703a2f2f73616d792e706c2f6d616773706f6f662f6d6167312e706e67)

On a 50% duty cycle I get about 12Vpp on average, that should be about 9x more power.
![image](https://user-images.githubusercontent.com/4208594/216775570-964f3c8f-be6c-4cb9-bfed-bb7817960b0b.png)

I'm not holding my fingers crossed yet.

**Comment by zacharyweiss** [comment]
For the sake of posterity; to share comments given elsewhere:

Amazing work — initial tests look very promising. Much stronger response from an analog mag read-head I have, when compared to existing RFID Tx. Will see about dialing in duty cycle / pulse duration / other params this weekend.

**Comment by zacharyweiss** [comment]
At present, I'm freezing internal TX work in favor of polishing GPIO tx, UI/UX, & UART read; in the event I begin digging into internal TX again, will reopen this.
