### ISSUE TITLE
Exiting magspoof wip clears tracks

### ISSUE THREAD

**Issue by qqmajikpp** [zacharyweiss/magspoof_flipper#6]
So I can add entries and track info. I can attempt to emulate this info. Once I leave magspoof and come back, I'll try to load a saved entry and find all the tack data is missing.

**Comment by zacharyweiss** [comment]
This was a known bug, but should've been fixed a few commits ago. Are you compiling from my GH or using the FAP RM is distributing? He doesn't submodule my code, and as such there's no guarantee it is up to date.

**Comment by Ludeco27** [comment]
I need a track2 nfc payment simulator that simulates payments, and the voucher comes out, if you have it, get in touch
