### ISSUE TITLE
Ability to change IO pins

### ISSUE THREAD

**Issue by RChadwick7** [zacharyweiss/magspoof_flipper#8]
I wanted to make a combination Magspoof/NRF24L01 module. Unfortunately, they use the same pins.

**Comment by zacharyweiss** [comment]
Long overdue reply on my part; plan to do some cleanup of the code over the coming weeks — this is one of the features I intend to include.

**Comment by zacharyweiss** [comment]
@RChadwick7, one can now choose the pins!
